Reload

diff --git a/0x1A-application_server/4-reload_gunicorn_no_downtime b/0x1A-application_server/4-reload_gunicorn_no_downtime
--- a/0x1A-application_server/4-reload_gunicorn_no_downtime
+++ b/0x1A-application_server/4-reload_gunicorn_no_downtime
@@ -1,4 +1,12 @@
 #!/usr/bin/env bash
 # Gracefully reloads Gunicorn.
 
-pgrep gunicorn | xargs kill -HUP
+if pgrep gunicorn >/dev/null; then
+	echo "Reloading Gunicorn gracefully..."
+	pkill -HUP gunicorn
+	sleep 2
+	pgrep gunicorn >/dev/null && echo "Gunicorn reloaded successfully." || echo "Gunicorn failed to reload."
+else
+	echo "Gunicorn is not running."
+	exit 1
+fi
